pub mod cache_cmd;
pub mod doctor_cmd;
pub mod inventory;
pub mod plugin_cmd;
pub mod prune_cmd;
pub mod setup;
pub mod setup_ci_cmd;
pub mod uninstall_cmd;
pub mod update_cmd;
pub mod upgrade_cmd;
pub mod use_cmd;

pub use cache_cmd::run_cache;
pub use doctor_cmd::run_doctor;
pub use inventory::{print_inventory, print_inventory_json};
pub use plugin_cmd::run_plugin;
pub use prune_cmd::run_prune;
pub use setup::{install_shims, print_completions, print_setup, resolve_setup_shell};
pub use setup_ci_cmd::{print_sync_outcome, run_setup_ci};
pub use uninstall_cmd::run_uninstall;
pub use update_cmd::run_update;
pub use upgrade_cmd::run_upgrade;
pub use use_cmd::{run_install, run_use};
