[package]
name = "jolter-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "jolter"
path = "src/main.rs"

[[bin]]
name = "jolter-shim"
path = "src/shim.rs"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
inquire.workspace = true
jolter-core = { path = "../core" }
jolter-doctor = { path = "../doctor" }
jolter-plugin = { path = "../plugin" }
jolter-runtime = { path = "../runtime" }
jolter-shim = { path = "../shim" }
jolter-storage = { path = "../storage" }
serde_json.workspace = true
semver.workspace = true
thiserror.workspace = true

[dev-dependencies]
jolter-resolver = { path = "../resolver" }
tempfile.workspace = true

[target.'cfg(windows)'.build-dependencies]
winres.workspace = true

[lints]
workspace = true
